// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEquation() {
  return window['go']['backend']['Equation']['CreateEquation']();
}

export function GetEquations(arg1) {
  return window['go']['backend']['Equation']['GetEquations'](arg1);
}

export function NewEquation() {
  return window['go']['backend']['Equation']['NewEquation']();
}

export function SaveEquations(arg1, arg2) {
  return window['go']['backend']['Equation']['SaveEquations'](arg1, arg2);
}
