// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateEquation():Promise<backend.Equation>;

export function GetEquations(arg1:string):Promise<Array<backend.Equation>>;
