// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateWorkspace(arg1:number):Promise<void>;

export function GetWorkspaces():Promise<Array<backend.Workspace>>;
