// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWorkspace(arg1) {
  return window['go']['backend']['Workspace']['CreateWorkspace'](arg1);
}

export function GetWorkspaces() {
  return window['go']['backend']['Workspace']['GetWorkspaces']();
}
